### ISSUE TITLE
Implement NRB tx limits on pegged Token

### ISSUE THREAD

**Issue by nepalbitcoin** [Nepal-Blockchain/NepalFoodBank#1]
We've to implement tx limits as per NRB tx limits on MPS, MFS and "E-wallet/ Mobile wallet/ Digital wallet" parts. Whole classification is vague + stupid, but that's what we've now.

[https://ipfs.io/ipfs/QmcK2yRLjWojkQjMDuTEngPzKyXabinZKK9VhwjGJjphxh ![image](https://user-images.githubusercontent.com/13423662/53411336-4e4a4280-39ee-11e9-96c5-3bb7e6c36d60.png)](https://ipfs.io/ipfs/QmcK2yRLjWojkQjMDuTEngPzKyXabinZKK9VhwjGJjphxh)

**Comment by hemantasapkota** [comment]
Some background information would be useful to understand what we're doing here.

**Comment by nepalbitcoin** [comment]
@hemantasapkota check you email.. we'll get all docs in /docs dir soon.

**Comment by nepalbitcoin** [comment]
@hemantasapkota 
Logic check?
8ca14ad ++
```
    function checkLimit(DATA storage data, address from, uint256 value) private {
        // ree ree check logic
        if (data.user[from].monthTimer < (now - 30 days)) {
            data.user[from].monthTimer = now;
            data.user[from].monthTx = value;
        } else {
            require(data.user[from].monthTx <= data.monthlyLimit, "OVER_MONTHLY_LIMIT");
            data.user[from].monthTx = (data.user[from].monthTx).add(value);
        }

        if (data.user[from].dayTimer < (now - 24 hours)) {
            data.user[from].dayTimer = now;
            data.user[from].dayTx = value;
        } else {
            require(data.user[from].dayTx <= data.dailyLimit, "OVER_DAILY_LIMIT");
            data.user[from].dayTx = (data.user[from].dayTx).add(value);
        }
    }
```
